import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '../../components/navigation'
import projectImage from '../../public/animation.jpg'
import Contact from '../../components/contact'

import joya from '../../public/joya.gif'
import cc from '../../public/cc.gif'
import levis from '../../public/levis.gif'
import uke from '../../public/uke.gif'
import broncosHat from '../../public/broncos-hat.gif'
import frog from '../../public/frog.gif'
import singersFan from '../../public/singers-fan.gif'

export default function Home() {
    const [toggle, setToggle] = useState(false)
    const handleToggle = () => {
        setToggle(!toggle)
    }

    return (
        <div className="min-h-screen relative">
            <Head>
                <title>Projects | 96 Broncos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="sr-only">96 Broncos Project</h1>
            <div className="flex flex-col justify-center min-h-screen">
                <div className="grid grid-cols-12 py-5 lg:py-10 relative">
                    <Navigation toggle={handleToggle} />
                    <div className="col-start-1 lg:col-start-2 col-span-12 lg:col-span-10 relative px-[5%] pt-5 lg:pt-10">
                        <Image
                            src={projectImage}
                            alt=""
                            // width={500} automatically provided
                            // height={500} automatically provided
                            blurDataURL="data:..."
                            placeholder="blur"
                        />
                        <div className="absolute top-[22%] left-[17%] right-[17%] bottom-[15%] bg-red-50">
                            <div className="animation-grid gap-1 h-[60%]">
                                <a
                                    href="https://www.instagram.com/p/ClR_giIp3Rb/"
                                    target="_blank"
                                    className="joya"
                                >
                                    <Image
                                        className=""
                                        src={joya}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>
                                <a
                                    href="https://www.instagram.com/p/CUD26cIFDb5/"
                                    target="_blank"
                                    className="cc"
                                >
                                    <Image
                                        className=""
                                        src={cc}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>
                                <div target="_blank" className="levis">
                                    <Image
                                        className=""
                                        src={levis}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                                <a
                                    href="https://www.instagram.com/p/CcmNOjrMnoP/"
                                    target="_blank"
                                    className="uke"
                                >
                                    <Image
                                        className=""
                                        src={uke}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>
                                <a
                                    href="https://www.instagram.com/p/CYSS2gAsMfi/"
                                    target="_blank"
                                    className="broncos-hat"
                                >
                                    <Image
                                        className=""
                                        src={broncosHat}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>
                            </div>
                            <div className="grid grid-cols-2 h-[40%] gap-x-1 mt-1">
                                <a
                                    href="https://www.instagram.com/p/CVd8ap6MN3H/"
                                    target="_blank"
                                    className="relative"
                                >
                                    <Image
                                        className="absolute inset-0 object-cover w-full h-full"
                                        src={frog}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>

                                <a
                                    href="https://www.instagram.com/p/CffN4daJTtv/"
                                    target="_blank"
                                    className="relative"
                                >
                                    <Image
                                        className="absolute inset-0 object-cover w-full h-full"
                                        src={singersFan}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {toggle && <Contact toggle={handleToggle} />}
        </div>
    )
}
