import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '../../components/navigation'
import projectImage from '../../public/animation.jpg'
import Contact from '../../components/contact'

import joya from '../../public/joya.gif'
import cc from '../../public/cc.gif'
import levis from '../../public/levis.gif'
import uke from '../../public/uke.gif'
import broncosHat from '../../public/broncos-hat.gif'
import frog from '../../public/frog.gif'
import singersFan from '../../public/singers-fan.gif'

export default function Home() {
    const [isContactOpen, setIsContactOpen] = useState(false)
    const toggleMenu = () => setIsContactOpen(!isContactOpen)

    return (
        <div className="min-h-screen relative">
            <Head>
                <title>Projects | 96 Broncos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="sr-only">96 Broncos Project</h1>
            <div className="flex flex-col justify-center min-h-screen">
                <div className="grid grid-cols-12 py-[5vw]">
                    <div className="col-start-1 lg:col-start-2 col-span-12 lg:col-span-10 relative px-[6.5%] pt-[3.5%]">
                        <Image
                            src={projectImage}
                            alt=""
                            // width={500} automatically provided
                            // height={500} automatically provided
                            blurDataURL="data:..."
                            placeholder="blur"
                        />
                        <div className="absolute top-[22%] left-[17%] right-[17%] bottom-[15%] bg-red-50">
                            <div className="animation-grid gap-1 h-[60%]">
                                <div className="joya">
                                    <Image
                                        className=""
                                        src={joya}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                                <div className="cc">
                                    <Image
                                        className=""
                                        src={cc}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                                <div className="levis">
                                    <Image
                                        className=""
                                        src={levis}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                                <div className="uke">
                                    <Image
                                        className=""
                                        src={uke}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                                <div className="broncos-hat">
                                    <Image
                                        className=""
                                        src={broncosHat}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                            </div>
                            <div className="grid grid-cols-2 h-[40%] gap-x-1 mt-1">
                                <div className="relative">
                                    <Image
                                        className="absolute inset-0 object-cover w-full h-full"
                                        src={frog}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>

                                <div className="relative">
                                    <Image
                                        className="absolute inset-0 object-cover w-full h-full"
                                        src={singersFan}
                                        alt=""
                                        // width={500} automatically provided
                                        // height={500} automatically provided
                                        blurDataURL="data:..."
                                        placeholder="blur"
                                    />
                                </div>
                            </div>
                        </div>

                        <button
                            onClick={toggleMenu}
                            isContactOpen={false}
                            className="absolute top-[18%] right-[7%] w-1/4 h-[5%]"
                        >
                            <span className="sr-only">Contact Me</span>
                        </button>
                        <Link
                            href="https://www.instagram.com/anton___/"
                            className="absolute top-[12%] right-[33%] w-[2%] h-[1.5%]"
                        >
                            <span className="sr-only">Instagram</span>
                        </Link>
                    </div>
                </div>
            </div>
            {isContactOpen && <Contact isContactOpen={setIsContactOpen} />}
        </div>
    )
}
