import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '../../components/navigation'
import projectImage from '../../public/96_web.jpg'
import Contact from '../../components/contact'

export default function Home() {
    const [toggle, setToggle] = useState(false)
    const handleToggle = () => {
        setToggle(!toggle)
    }

    return (
        <div className="min-h-screen relative">
            <Head>
                <title>Projects | 96 Broncos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="sr-only">96 Broncos Project</h1>
            <div className="flex flex-col justify-center min-h-screen">
                <div className="grid grid-cols-12 py-5 lg:py-10 relative">
                    <Navigation toggle={handleToggle} />
                    <div className="col-start-1 lg:col-start-2 col-span-12 lg:col-span-10 relative px-[5%] pt-5 lg:pt-10">
                        <Image
                            src={projectImage}
                            alt=""
                            // width={500} automatically provided
                            // height={500} automatically provided
                            blurDataURL="data:..."
                            placeholder="blur"
                        />

                        <a
                            href="https://www.instagram.com/p/CYSS2gAsMfi/"
                            target="_blank"
                            className="absolute top-[6.5%] left-[11%] w-[20%] h-[20%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CoaHCp7JKQ_/"
                            target="_blank"
                            className="absolute top-[6.5%] right-[25%] w-[10.5%] h-[23%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CIWqAkQlNCG/"
                            target="_blank"
                            className="absolute top-[21.5%] right-[10%] w-[10.5%] h-[21%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CR2OKa7lOq2/"
                            target="_blank"
                            className="absolute top-[37.5%] right-[38%] w-[21.5%] h-[17%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CWEsfqRFYj5/"
                            target="_blank"
                            className="absolute top-[58.5%] left-[15%] w-[43.5%] h-[24%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CIZUHnvljcx/"
                            target="_blank"
                            className="absolute top-[43.5%] right-[8%] w-[29.5%] h-[42%]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                    </div>
                </div>
            </div>
            {toggle && <Contact toggle={handleToggle} />}
        </div>
    )
}
