import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '../../components/navigation'
import projectImage from '../../public/illustration-web.jpg'
import Contact from '../../components/contact'

export default function Home() {
    const [toggle, setToggle] = useState(false)
    const handleToggle = () => {
        setToggle(!toggle)
    }

    return (
        <div className="min-h-screen relative">
            <Head>
                <title>Projects | Illustration</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="sr-only">Illustration Project</h1>
            <div className="flex flex-col justify-center min-h-screen">
                <div className="grid grid-cols-12 py-5 lg:py-10 relative">
                    <Navigation toggle={handleToggle} />
                    <div className="col-start-1 lg:col-start-2 col-span-12 lg:col-span-10 relative px-[5%] pt-5 lg:pt-10">
                        <Image
                            src={projectImage}
                            alt=""
                            // width={500} automatically provided
                            // height={500} automatically provided
                            blurDataURL="data:..."
                            placeholder="blur"
                        />

                        <a
                            href="https://www.instagram.com/p/Cc1Lnw-pphH/"
                            target="_blank"
                            className="absolute top-[37%] left-[4%] w-[35%] h-[27%] transform rotate-[-14deg] z-[4]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CiQyEa0JaBX/"
                            target="_blank"
                            className="absolute top-[32%] left-[42%] w-[35%] h-[27%] transform rotate-[-13deg] z-[2]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CffN4daJTtv/"
                            target="_blank"
                            className="absolute top-[13%] right-[5%] w-[29%] h-[28%] transform rotate-[-13deg] z-[1]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CEIP2z8FfYD/"
                            target="_blank"
                            className="absolute top-[58%] left-[24%] w-[35%] h-[27%] transform rotate-[-14deg] z-[3]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/CEIP2z8FfYD/"
                            target="_blank"
                            className="absolute top-[42%] right-[0%] w-[30%] h-[42%] transform rotate-[-14deg] z-[1]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                        <a
                            href="https://www.instagram.com/p/Cc1Lnw-pphH/"
                            target="_blank"
                            className="absolute top-[75%] right-[13%] w-[35%] h-[27%] transform rotate-[-14deg] z-[2]"
                        >
                            <span className="sr-only">View on instagram</span>
                        </a>
                    </div>
                </div>
            </div>
            {toggle && <Contact toggle={handleToggle} />}
        </div>
    )
}
