import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import indexImage from '../public/index-image.png'
import Contact from '../components/contact'

export default function Home() {
    const [toggle, setToggle] = useState(false)
    const handleToggle = () => {
        setToggle(!toggle)
    }

    return (
        <div className="min-h-screen relative">
            <Head>
                <title>Allan Khorsheed | Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="sr-only">Allan Khorsheed</h1>
            <div className="flex flex-col justify-center min-h-screen">
                <div className="grid grid-cols-12 py-[5vw]">
                    <div className="col-start-1 lg:col-start-2 col-span-12 lg:col-span-10 relative">
                        <Image
                            src={indexImage}
                            alt=""
                            blurDataURL="data:..."
                            placeholder="blur"
                        />

                        <button
                            onClick={handleToggle}
                            className="absolute top-[18%] right-[7%] w-1/4 h-[5%]"
                        >
                            <span className="sr-only">Contact Me</span>
                        </button>
                        <Link
                            href="https://www.instagram.com/anton___/"
                            className="absolute top-[12%] right-[33%] w-[2%] h-[1.5%]"
                        >
                            <span className="sr-only">Instagram</span>
                        </Link>
                        <Link
                            href="https://www.instagram.com/anton___/"
                            className="absolute top-[25%] right-[33%] w-[2%] h-[1.5%]"
                        >
                            <span className="sr-only">Instagram</span>
                        </Link>
                        <Link
                            href="/projects/levis"
                            className="absolute top-[33%] left-[11%] w-[44%] h-[11%]"
                        >
                            <span className="sr-only">Levis Project</span>
                        </Link>
                        <Link
                            href="/projects/vogue"
                            className="absolute top-[45%] left-[11%] w-[44%] h-[12%]"
                        >
                            <span className="sr-only">Vogue Project</span>
                        </Link>
                        <Link
                            href="/projects/elios"
                            className="absolute top-[36%] right-[10%] w-[34%] h-[9%]"
                        >
                            <span className="sr-only">Elios Project</span>
                        </Link>
                        <Link
                            href="/projects/broncos"
                            className="absolute top-[23%] right-[10%] w-[34%] h-[12%]"
                        >
                            <span className="sr-only">96 Broncos Project</span>
                        </Link>
                        <Link
                            href="/projects/vice"
                            className="absolute top-[46%] right-[10%] w-[34%] h-[11%]"
                        >
                            <span className="sr-only">Vice Project</span>
                        </Link>
                        <Link
                            href="/projects/singers"
                            className="absolute top-[59%] right-[9%] w-[34%] h-[18%] transform rotate-2"
                        >
                            <span className="sr-only">Singers Project</span>
                        </Link>
                    </div>
                </div>
            </div>
            {toggle && <Contact toggle={handleToggle} />}
        </div>
    )
}
